# Generated by Django 5.2 on 2025-12-29 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité en stock (tonnes)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_date', models.DateField(verbose_name="Date d'extraction")),
                ('quantity_tonnes', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité (tonnes)')),
                ('quality_grade', models.CharField(blank=True, max_length=50, verbose_name='Grade de qualité')),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('operator', models.ForeignKey(limit_choices_to={'role__in': ['agent_minier', 'responsable_site']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Extraction',
                'verbose_name_plural': 'Extractions',
                'ordering': ['-extraction_date'],
                'indexes': [models.Index(fields=['site', '-extraction_date'], name='extraction__site_id_3a5a00_idx'), models.Index(fields=['status'], name='extraction__status_fb0087_idx')],
            },
        ),
    ]
