# Generated by Django 5.2 on 2025-12-29 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de référence')),
                ('quantity_exported', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité exportée (tonnes)')),
                ('destination_country', models.CharField(max_length=100, verbose_name='Pays de destination')),
                ('buyer', models.CharField(max_length=200, verbose_name='Acheteur')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire ($)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total ($)')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('expedie', 'Expédié'), ('livre', 'Livré')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_paye', 'Partiellement payé'), ('entierement_paye', 'Entièrement payé')], default='en_attente', max_length=20, verbose_name='Statut du paiement')),
                ('export_date', models.DateField(verbose_name="Date d'export")),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Livraison prévue')),
                ('actual_delivery', models.DateField(blank=True, null=True, verbose_name='Livraison réelle')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'douane'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exports', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='transport.transport', verbose_name='Transport')),
            ],
            options={
                'verbose_name': 'Export',
                'verbose_name_plural': 'Exports',
                'ordering': ['-export_date'],
            },
        ),
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', "Certificat d'origine"), ('invoice', 'Facture'), ('bill_of_lading', 'Connaissement'), ('packing_list', 'Liste de colisage'), ('inspection_report', "Rapport d'inspection"), ('customs_clearance', 'Dédouanement'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('document_file', models.FileField(upload_to='export_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xlsx'])], verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléchargé le')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='export.export', verbose_name='Export')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': "Document d'export",
                'verbose_name_plural': "Documents d'export",
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['status'], name='export_expo_status_1808c5_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['-export_date'], name='export_expo_export__d32cce_idx'),
        ),
    ]
