# Generated by Django 5.2 on 2025-12-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_extraction', 'Total extractions'), ('total_transport', 'Total transports'), ('total_export', 'Total exports'), ('active_sites', 'Sites actifs'), ('alerts_count', "Nombre d'alertes"), ('revenue', "Chiffre d'affaires")], max_length=50, verbose_name='Type de métrique')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': 'Métrique du dashboard',
                'verbose_name_plural': 'Métriques du dashboard',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['metric_type', '-period_end'], name='dashboard_d_metric__1d030f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('report_type', models.CharField(choices=[('extraction_summary', 'Résumé des extractions'), ('transport_tracking', 'Suivi des transports'), ('export_analysis', 'Analyse des exportations'), ('environment_report', 'Rapport environnemental'), ('financial_report', 'Rapport financier'), ('audit_log', "Journal d'audit")], max_length=50, verbose_name='Type de rapport')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Format')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Chemin du fichier')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', '-generated_at'], name='dashboard_r_report__4833be_idx')],
            },
        ),
    ]
