# Generated by Django 5.2.9 on 2026-01-06 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Visualisation'), ('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression'), ('export', 'Export'), ('import', 'Import'), ('share', 'Partage')], max_length=20, verbose_name='Action')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': "Journal d'activité du tableau de bord",
                'verbose_name_plural': "Journaux d'activité des tableaux de bord",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('layout_type', models.CharField(choices=[('default', 'Défaut'), ('custom', 'Personnalisé'), ('role_based', 'Par rôle')], default='custom', max_length=20, verbose_name='Type de disposition')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration de la disposition')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('agent_minier', 'Agent Minier'), ('responsable_site', 'Responsable Site'), ('chauffeur', 'Chauffeur/Transporteur'), ('douane', 'Responsable Douane'), ('environnement', 'Responsable Environnement'), ('lecteur', 'Lecteur/Visiteur')], max_length=50, null=True, verbose_name='Rôle utilisateur')),
                ('is_default', models.BooleanField(default=False, verbose_name='Disposition par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Disposition de tableau de bord',
                'verbose_name_plural': 'Dispositions de tableaux de bord',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('system', 'Système')], default='light', max_length=50, verbose_name='Thème')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('default_filters', models.JSONField(blank=True, default=dict, verbose_name='Filtres par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Paramètre utilisateur de tableau de bord',
                'verbose_name_plural': 'Paramètres utilisateur des tableaux de bord',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('widget_type', models.CharField(choices=[('chart_line', 'Graphique linéaire'), ('chart_bar', 'Graphique à barres'), ('chart_pie', 'Graphique circulaire'), ('metric_card', 'Carte de métrique'), ('data_table', 'Tableau de données'), ('activity_feed', "Flux d'activité"), ('alert_list', "Liste d'alertes"), ('map_view', 'Vue carte')], max_length=50, verbose_name='Type de widget')),
                ('size', models.CharField(choices=[('small', 'Petit (1x1)'), ('medium', 'Moyen (2x1)'), ('large', 'Grand (2x2)'), ('xlarge', 'Très grand (3x2)')], default='medium', max_length=10, verbose_name='Taille')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtres')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Widget de tableau de bord',
                'verbose_name_plural': 'Widgets de tableaux de bord',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ligne')),
                ('col', models.PositiveIntegerField(verbose_name='Colonne')),
                ('size_x', models.PositiveIntegerField(default=1, verbose_name='Largeur')),
                ('size_y', models.PositiveIntegerField(default=1, verbose_name='Hauteur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Position de widget',
                'verbose_name_plural': 'Positions de widgets',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='dashboardmetric',
            options={'ordering': ['-period_end', 'metric_type'], 'verbose_name': 'Métrique du tableau de bord', 'verbose_name_plural': 'Métriques du tableau de bord'},
        ),
        migrations.RemoveField(
            model_name='dashboardmetric',
            name='calculated_at',
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metrics', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_type',
            field=models.CharField(choices=[('extraction_total', 'Total extractions'), ('extraction_monthly', 'Extractions mensuelles'), ('transport_total', 'Total transports'), ('transport_pending', 'Transports en attente'), ('export_total', 'Total exports'), ('export_pending', 'Exports en attente'), ('site_active', 'Sites actifs'), ('alerts_open', 'Alertes ouvertes'), ('revenue_monthly', 'Revenu mensuel'), ('user_activity', 'Activité utilisateur')], max_length=50, verbose_name='Type de métrique'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='value',
            field=models.JSONField(verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('extraction_summary', 'Résumé des extractions'), ('transport_tracking', 'Suivi des transports'), ('export_analysis', 'Analyse des exportations'), ('environment_report', 'Rapport environnemental'), ('financial_report', 'Rapport financier'), ('audit_log', "Journal d'audit"), ('custom', 'Personnalisé')], max_length=50, verbose_name='Type de rapport'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['is_active'], name='dashboard_d_is_acti_2dc342_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardmetric',
            constraint=models.UniqueConstraint(fields=('metric_type', 'period_start', 'period_end'), name='unique_metric_period'),
        ),
        migrations.AddField(
            model_name='dashboardactivitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dashboardactivitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_layouts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='dashboardusersettings',
            name='custom_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='dashboard.dashboardlayout', verbose_name='Disposition personnalisée'),
        ),
        migrations.AddField(
            model_name='dashboardusersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='dashboard_widgets', to='auth.group', verbose_name='Rôles autorisés'),
        ),
        migrations.AddField(
            model_name='dashboardwidgetposition',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_positions', to='dashboard.dashboardlayout', verbose_name='Disposition'),
        ),
        migrations.AddField(
            model_name='dashboardwidgetposition',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='dashboard.dashboardwidget', verbose_name='Widget'),
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='widgets',
            field=models.ManyToManyField(related_name='layouts', through='dashboard.DashboardWidgetPosition', to='dashboard.dashboardwidget', verbose_name='Widgets'),
        ),
        migrations.AddIndex(
            model_name='dashboardactivitylog',
            index=models.Index(fields=['-timestamp'], name='dashboard_d_timesta_d2686b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardactivitylog',
            index=models.Index(fields=['user', '-timestamp'], name='dashboard_d_user_id_23c066_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardactivitylog',
            index=models.Index(fields=['action', '-timestamp'], name='dashboard_d_action_7907ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidgetposition',
            unique_together={('layout', 'row', 'col'), ('layout', 'widget')},
        ),
        migrations.AddConstraint(
            model_name='dashboardlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('role',), name='unique_default_role_layout'),
        ),
    ]
