# Generated by Django 5.2 on 2025-12-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(max_length=50, unique=True, verbose_name='Type de mesure')),
                ('warning_threshold', models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Seuil d'avertissement")),
                ('danger_threshold', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Seuil de danger')),
                ('critical_threshold', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Seuil critique')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Seuil environnemental',
                'verbose_name_plural': 'Seuils environnementaux',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('pm25', 'PM2.5 (μg/m³)'), ('pm10', 'PM10 (μg/m³)'), ('co2', 'CO2 (ppm)'), ('noise', 'Bruit (dB)'), ('water_ph', "pH de l'eau"), ('water_turbidity', 'Turbidité (NTU)'), ('soil_quality', 'Qualité du sol'), ('air_quality', "Qualité de l'air")], max_length=50, verbose_name='Type de mesure')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valeur')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('measurement_date', models.DateTimeField(verbose_name='Date/heure de mesure')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu de mesure')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('measured_by', models.ForeignKey(limit_choices_to={'role': 'environnement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mesuré par')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_measures', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Mesure environnementale',
                'verbose_name_plural': 'Mesures environnementales',
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('threshold_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Seuil dépassé')),
                ('actual_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valeur réelle')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger'), ('critical', 'Critique')], default='warning', max_length=20, verbose_name='Niveau de sévérité')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('resolved', 'Résolu'), ('acknowledged', 'Reconnu')], default='active', max_length=20, verbose_name='Statut')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Déclenché le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'environnement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_alerts', to='sites.site', verbose_name='Site')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='environment.environmentmeasure', verbose_name='Mesure')),
            ],
            options={
                'verbose_name': 'Alerte environnementale',
                'verbose_name_plural': 'Alertes environnementales',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='environmentmeasure',
            index=models.Index(fields=['site', '-measurement_date'], name='environment_site_id_348702_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentmeasure',
            index=models.Index(fields=['measurement_type'], name='environment_measure_359513_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalert',
            index=models.Index(fields=['site', 'status'], name='environment_site_id_411016_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalert',
            index=models.Index(fields=['severity'], name='environment_severit_d5909e_idx'),
        ),
    ]
