import sqlite3

db='db.sqlite3'
conn=sqlite3.connect(db)
cur=conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
tables=cur.fetchall()
print('TABLES:', tables)
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'accounts%';")
print('ACCOUNTS-TABLES:', cur.fetchall())
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'sites%';")
print('SITES-TABLES:', cur.fetchall())
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'extraction%';")
print('EXTRACTION-TABLES:', cur.fetchall())
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'transport%';")
print('TRANSPORT-TABLES:', cur.fetchall())
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'export%';")
print('EXPORT-TABLES:', cur.fetchall())
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'environment%';")
print('ENVIRONMENT-TABLES:', cur.fetchall())
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'notifications%';")
print('NOTIFICATIONS-TABLES:', cur.fetchall())
cur.execute("SELECT count(*) FROM sqlite_master WHERE name='django_migrations'")
print('HAS django_migrations:', cur.fetchone()[0])
conn.close()
