# Generated by Django 5.2 on 2025-12-29 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du site')),
                ('mineral_type', models.CharField(choices=[('bauxite', 'Bauxite'), ('or', 'Or'), ('diamant', 'Diamant'), ('fer', 'Fer'), ('cuivre', 'Cuivre'), ('autre', 'Autre')], max_length=20, verbose_name='Type de minerai')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('clos', 'Clôturé')], default='actif', max_length=20, verbose_name='Statut')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacité de production (tonnes)')),
                ('operational_since', models.DateField(verbose_name='En opération depuis')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de permis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable_site'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Site minier',
                'verbose_name_plural': 'Sites miniers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteOperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_history', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': "Historique d'opération",
                'verbose_name_plural': "Historiques d'opération",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['status'], name='sites_site_status_79a98b_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['mineral_type'], name='sites_site_mineral_437ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='siteoperationhistory',
            index=models.Index(fields=['site', '-timestamp'], name='sites_siteo_site_id_942696_idx'),
        ),
    ]
