# Generated by Django 5.2 on 2025-12-29 22:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='QR Code unique')),
                ('departure_location', models.CharField(max_length=200, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Date/heure de départ')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name="Date/heure d'arrivée")),
                ('quantity_transported', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité transportée (tonnes)')),
                ('status', models.CharField(choices=[('depart_planifie', 'Départ planifié'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('annule', 'Annulé')], default='depart_planifie', max_length=20, verbose_name='Statut')),
                ('gps_tracking', models.BooleanField(default=False, verbose_name='Suivi GPS activé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='extraction.extraction', verbose_name='Extraction')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['-departure_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='transport.transport', verbose_name='Transport')),
            ],
            options={
                'verbose_name': 'Position transport',
                'verbose_name_plural': 'Positions transport',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Immatriculation')),
                ('truck_type', models.CharField(max_length=100, verbose_name='Type de camion')),
                ('capacity_tonnes', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacité (tonnes)')),
                ('owner', models.CharField(max_length=200, verbose_name='Propriétaire')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('maintenance', 'En maintenance'), ('retire', 'Retiré')], default='actif', max_length=20, verbose_name='Statut')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Dernière inspection')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur assigné')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camions',
                'ordering': ['registration_number'],
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.truck', verbose_name='Camion'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['qr_code'], name='transport_t_qr_code_63ca65_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['status'], name='transport_t_status_cb5b34_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['extraction'], name='transport_t_extract_b7a0e0_idx'),
        ),
    ]
