# Generated by Django 5.2 on 2025-12-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email du destinataire')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('body', models.TextField(verbose_name='Corps du message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Programmé pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Notification email',
                'verbose_name_plural': 'Notifications emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_b152cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('extraction', 'Extraction'), ('transport', 'Transport'), ('export', 'Export'), ('environment', 'Environnement'), ('alert', 'Alerte'), ('system', 'Système')], max_length=20, verbose_name='Type de notification')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Priorité')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet lié")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['-sent_at'], name='notificatio_sent_at_789d15_idx')],
            },
        ),
    ]
